server:
  port: 80
spring:
  application:
    name: cloud-consumer-payment
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
      host: localhost
      port: 8500
